name: CI Test
on:
  push:
    branches: ["main"]
    paths: ["install/*.*"]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up NVGT
        uses: harrymkt/setup-nvgt@v1.0.5
      - name: Install NVGTPM
        run: |
          curl -fsSL https://raw.githubusercontent.com/harrymkt/nvgtpm/main/install/dev.sh | bash
      - name: Post Tests
        run: |
          nvgtpm update -bks
          nvgtpm install nvgtpm
          nvgtpm list
          nvgtpm search nvgtpm
          nvgtpm cache status "*"
          nvgtpm status
          echo "retrieving syntax..."
          nvgtpm decl nvgtpm
