name: CI Test
on:
  push:
    branches: ["main"]
    paths: ["install/*.*"]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up NVGT
        uses: harrymkt/setup-nvgt@v1.0.6
      - name: Install NVGTPM
        run: |
          curl -fsSL https://raw.githubusercontent.com/harrymkt/nvgtpm/main/install/dev.sh | bash
      - name: Post Tests
        run: |
          nvgtpm program about
          nvgtpm update -bks
          nvgtpm install nvgtpm form
          nvgtpm list
          nvgtpm search nvgtpm
          nvgtpm cache status "*"
          nvgtpm status
          echo "retrieving syntax..."
          nvgtpm decl nvgtpm
          nvgtpm cache rm "*"
