name: Auto-Submit to Community Bucket
env:
  bucket_repo: "harrymkt/nvgtpm_bucket_main"
  app_name: "nvgtpm"
on:
  push:
    branches: [main, master]
    # Triggers dynamically based on source paths
    paths: ["modules/*.json"]
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Checkout Bucket Upstream
        uses: actions/checkout@v7
        with:
          repository: ${{ env.bucket_repo }}
          token: ${{ secrets.PAT }}
          path: bucket
      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
      - name: Build
        id: builder
        run: |
          cd modules
          python ci.py
      - name: Add JSON into Bucket Directory
        run: |
          # Dynamically extract the directory path from the target file path
          TARGET_DIR=$(dirname "bucket/json/${{ env.app_name }}.json")
          mkdir -p "$TARGET_DIR"
          # Copy the file
          cp "modules/${{ env.app_name }}.json" "$TARGET_DIR/${{ env.app_name }}.json"
      - name: Publish Automated Modules Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            modules/*.zip
          draft: false
          prerelease: false
          repository: "${{ env.bucket_repo }}"
          token: ${{ secrets.PAT }}
          tag_name: "builtin"
          body: "${{ steps.builder.outputs.pr_body }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PAT }}
          path: bucket
          commit-message: "Update Package Manifest of ${{ env.app_name }}"
          title: "Update Package JSON Manifest of ${{ env.app_name }}"
          branch: "app/${{ env.app_name }}"
          body: "${{ steps.builder.outputs.pr_body }}"
